/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c44bfb63-d35a-4e49-81bf-151e2e07666f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lj44Ar9gO",
    "aws_user_pools_web_client_id": "7geokrdefojedj4ju6ost07t0m",
    "oauth": {},
    "aws_user_files_s3_bucket": "herbtable060721145813-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://7aqio74fwzc5bavt7s5lldht4m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
